version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28

    environment:
      JVM_OPTS: -Xmx3200m


    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sdk/build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "sdk_stub/build.gradle" }}

      -  run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sdk/build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "sdk_stub/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: sdk/build/reports
          destination: reports
      - store_test_results:
          path: sdk/build/reports/tests/testDebugUnitTest

